#!/bin/sh
while true; do

	if ! pgrep python3 >/dev/null;
		then
		echo "currently not running"
		echo "starting /home/admin/Desktop/Vision/Main.py"
		sudo -u admin python3 /home/admin/Desktop/Vision/Main.py &
	fi
	sleep 5
done
exit 0
