#!/bin/sh

cvVersion="4.2.0"

echo "=======================\nCleaning up\n======================="
sudo apt-get -y purge wolfram-engine
sudo apt-get -y purge libreoffice*
sudo apt-get -y clean
sudo apt-get -y autoremove

echo "=======================\ninstalling Dependencies\n======================="
#base packages
sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y cmake gcc g++
sudo apt-get install -y build-essential pkg-config checkinstall

#python Dependencies
sudo apt-get install -y python3-dev python3-pip
sudo -H pip3 install -U pip numpy
sudo apt-get install -y python3-testresources

#Video stream Dependencies
sudo apt-get install -y libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
sudo apt-get install -y libxvidcore-dev libx264-dev
sudo apt-get install -y x264 v4l-utils
sudo apt-get install -y libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev

#Photo Dependencies
sudo apt-get install -y libpng-dev libpng12-dev
sudo apt-get install -y libjpeg-dev libjpeg8-dev
sudo apt-get install -y libtiff-dev libtiff5-dev
sudo apt-get install -y libjasper-dev 

#UI Dependencies
sudo apt-get install libfontconfig1-dev libcairo2-dev
sudo apt-get install libgdk-pixbuf2.0-dev libpango1.0-dev
sudo apt-get install -y libgtk2.0-dev libgtk-3-dev
sudo apt-get install -y libqtgui4 libqtwebkit4 libqt4-test python3-pyqt5

#optimization Dependencies
sudo apt-get install -y libatlas-base-dev gfortran

echo "=======================\nSetting up Virtual Enviroment\n======================="

echo "=======================\nDownloading Open CV\n======================="
mkdir installCV
cd installCV

git clone https://github.com/opencv/opencv.git
cd opencv
git checkout $cvVersion
cd ..

# cd ~/opencv
# $ mkdir build
# $ cd build
# $ cmake -D CMAKE_BUILD_TYPE=RELEASE \
#     -D CMAKE_INSTALL_PREFIX=/usr/local \
#     -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
#     -D ENABLE_NEON=ON \
#     -D ENABLE_VFPV3=ON \
#     -D BUILD_TESTS=OFF \
#     -D INSTALL_PYTHON_EXAMPLES=OFF \
#     -D OPENCV_ENABLE_NONFREE=ON \
#     -D CMAKE_SHARED_LINKER_FLAGS=-latomic \
#     -D BUILD_EXAMPLES=OFF ..
